### ISSUE TITLE
AuthnContextClassRef non valido

### ISSUE THREAD

**Issue by marco-maroni-spot-software** [italia/cie-aspnetcore#10]
Salve 
viste le nuove direttive, che permettono di accedere con la CIE anche a servizi che richiedono un livello di sicurezza 2, ho impostato nella libreria il parametro "SecurityLevel": 2, ma così facendo ottengo in fase di autenticazione l'errore "AuthnContextClassRef non valido". Errore che non compare se lascio il livello 3. 

Mi sfugge qualcosa?

Per info, sto facendo queste prove in produzione, quindi come fornitore di servizi già certificato e procedura di integrazione CIE completata e già in uso.

Grazie

**Comment by danielegiallonardo** [comment]
Salve,
la libreria non supporta le nuove direttive di CIE, l'unico SecurityLevel supportato e testato è il 3.
Dovrei trovare del tempo per adeguarla, appena possibile ci lavoro.
Nel frattempo contributi e PullRequest sono ben accetti :-)

**Comment by danielegiallonardo** [comment]
Ho pubblicato la versione 2.0.0 ed effettuato le modifiche richieste per supportare anche i livelli L1 ed L2, e con l'occasione ho aggiunto anche alcune feature, tra cui la gestione esplicita dei Log e la possibilità di specificare il SecurityLevel e il RequestMethod a runtime tramite CieEvents.
Ci sono alcune breaking changes nelle settings, puoi fare riferimento alla documentazione e all'esempio

**Comment by marco-maroni-spot-software** [comment]
Purtroppo ho ancora lo stesso problema, aggiornata la libreria allineati tutti i settings nuovi, spero di non aver fatto errori, ma da lo stesso identico problema. Se rirpristino la versione 1.2.0 login con Cie senza problemi.
Con la nuova libreira ho fatto la prova lasciando SecurityLevel a 3, nel caso fosse andato in porto avrei provato ad abbassarlo, ma anche con 3 da lo stesso errore ,che da con la vecchia libreria e SecurityLevel a 2.

**Comment by danielegiallonardo** [comment]
Purtroppo non ho modo di effettuare test in produzione, potresti provare a vedere se questa versione di prerelease risolve il problema?
https://www.nuget.org/packages/CIE.AspNetCore.Authentication/2.0.1-prerelease

**Comment by marco-maroni-spot-software** [comment]
Il problema sembra risolto con la 2.0.1-prerelease e SecurityLevel impostato a 3, ossia il comportamento è come la precedente libreria. 
Ma se provo ad impostare SecurityLevel a 2, nulla cambia, ossia la procedura richiede sempre lettura NFC della carta, è corretto? Non dovrebbe chiedermi solo le credenziali associate alla CIE username e pwd? Mi sfugge qualcosa?

**Comment by danielegiallonardo** [comment]
In che modo imposti il SecurityLevel? Da configurazione o da codice? Potresti postare il pezzo in cui lo imposti?

**Comment by marco-maroni-spot-software** [comment]
Da configurazione
![image](https://user-images.githubusercontent.com/6230180/230328363-c7454432-38d3-4ac3-849d-96811726bdbd.png)

**Comment by danielegiallonardo** [comment]
Dalla versione 2.x del package, il SecurityLevel è stato spostato nel livello "Cie" ed eliminato dalla sezione Provider, come da ChangeLog e da [README](https://github.com/italia/cie-aspnetcore#upgrade-dalla-versione-1x-alla-2x) 
Dovresti spostare quel settings sotto "Cie" e riprovare.

**Comment by marco-maroni-spot-software** [comment]
Impostato come da readme ma sembra non cambiare nulla

![image](https://user-images.githubusercontent.com/6230180/230332394-e7f23f2a-8807-4a23-b62d-665af1b7510e.png)

Ho anche provato a mettere un 99, così per vedere se mi dava errore, ma nulla, sembra proprio ingorarlo.

**Comment by danielegiallonardo** [comment]
Hai la possibilità di intercettare e decodificare la request che invii a CIE e verificare che effettivamente, al cambio del SecurityLevel, tale valore venga riportato correttamente nel campo AuthnContextClassRef?

**Comment by danielegiallonardo** [comment]
Ho verificato con un'app di test. Cambiando il valore di SecurityLevel questo viene correttamente riportato nella request.

**Comment by marco-maroni-spot-software** [comment]
Ok provo a fare qualche altra verifia, mi viene il dubbio che ci sia qualche altro attore che debba gestire questa nuova modalità con SecurityLever diverso da 3, per esempio il portale di federazione del governe per cie, possibile che loro ignorino questo parametro? Non so la butto lì

**Comment by danielegiallonardo** [comment]
E' probabile che non tutti i sistemi siano ancora allineati, l'introduzione dei livelli 1 e 2 è una modifica relativamente nuova.
Ad ogni modo pubblico una nuova versione del pacchetto che risolve il bug e chiudo la issue
