### ISSUE TITLE
Errore su Login CIE

### ISSUE THREAD

**Issue by mar-rossini** [italia/cie-aspnetcore#14]
Ciao a tutti,

continuo ad ottenere errore in fase di autenticazione con CIE.

Ho configurato il LogHandler come consigliato con i 4 metodi per le PostRequest e le Redirect Request:

```
.AddCie(options => {
    options.LoadFromConfiguration(configuration);
    options.Events.OnAuthenticationSuccess = async (s) => await s.HttpContext.RequestServices.GetRequiredService<CIEEventsInterceptor>().AuthenticationSuccess(s);
    options.ServiceProviders.AddRange(cieLoader.GetServiceProviders());
})
.AddLogHandler<AuthLogHandler>()
```

Sul portale di Federazione Erogatori risulta tutto Federato sia in pre-prod che in prod.

Gli step che seguo sono:

1. Entra con CIE
2. Prosegui con Smartphone
3. Inserisco numero CI
4. Scansione il QR
5. Avvicino la carta all'NFC
6. Ottengo ERRORE -> **Impossibile recuperare le informazioni dell'utente**

Dal log sembra tutto liscio:
Logga la richiesta verso https://preproduzione.idserver.servizicie.interno.gov.it/idp/profile/SAML2/POST/SSO
e poi
_AuthenticationScheme: Cie was challenged_

Se provo in ambiente di prod, invece, ottengo un errore:

**La richiesta non può essere soddisfatta poiché il messaggio ricevuto non rispetta i requisiti di sicurezza del servizio di accesso.**

Voi avete qualche suggerimento su come posso intercettare il problema? Qualsiasi consiglio è ben accetto.

Grazie per tutto il lavoro che fare

**Comment by danielegiallonardo** [comment]
Ciao,
perdonami, ma credo di non aver capito bene il problema. Chi restituisce l'errore "Impossibile recuperare le informazioni dell'utente"? Il sito CIE in fase di verifica delle credenziali? In tal caso è un problema al di fuori del controllo della libreria, possiamo farci poco.

**Comment by mar-rossini** [comment]
Ciao Daniele, sono Marco piacere :)

Ti ringrazio intanto per il supporto, l'errore che ottengo è praticamente questo su smartphone:

![Screen](https://github.com/italia/cie-aspnetcore/assets/149949193/9400d31d-d087-47a3-b064-bb03bc21f5b3)

Mi rendo conto che potrebbe non essere legato alla libreria, chiedevo un consulto se ci fosse un modo di debuggarlo internamente magari intercettando le risposte da CIE. Attualmente la challenge sembra dare 200

In caso negativo chiudi pure il ticket, grazie mille.

**Comment by danielegiallonardo** [comment]
La challenge da correttamente 200, tant'è che vieni redirezionato verso le pagine di CIE. Questa schermata in realtà è una pagina di errore sull'app CIE, pare non riesca a leggere i dati dalla carta. Ad ogni modo non dipende dalla libreria, l'errore avviene sul sito CIE.
